export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS'
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS'

export const CHANGE_SETTING_PANEL_STATE = 'CHANGE_SETTING_PANEL_STATE'
export const SHOW_COUNTERS = 'SHOW_COUNTERS'
export const UPDATE_PLAYER = 'UPDATE_PLAYER'
export const RESET_GAME = 'RESET_GAME'
export const TOGGLE_SCREEN = 'TOGGLE_SCREEN'
